### ISSUE TITLE
Tag 1.6.0 was published to Docker Hub but isn't on GitHub

### ISSUE THREAD

**Issue by gnarea** [zazukoians/docker-hitch#6]
You probably forgot to push the commit.

https://hub.docker.com/layers/zazukoians/hitch/1.6.0/images/sha256-6dc562f1222db339a0ed914b979214d6a62361e15f3af93d9e6120ebd0f4ac2f?context=explore

**Comment by ktk** [comment]
Oh thanks for noticing, I just pushed and from what I can see it's up now.

**Comment by gnarea** [comment]
Thanks!
