### ISSUE TITLE
Image takes up 85 MB instead of 8

### ISSUE THREAD

**Issue by gnarea** [zazukoians/docker-hitch#7]
The README says it's 8MB but it's 85+ according to Docker Hub: https://hub.docker.com/layers/zazukoians/hitch/1.6.0/images/sha256-6dc562f1222db339a0ed914b979214d6a62361e15f3af93d9e6120ebd0f4ac2f?context=explore

Not sure if this is a problem with the README or a bug.

**Comment by ktk** [comment]
IIRC I had the number from some overlay-calculator I once used but that seems to be wrong then. Do you see anything I forgot to clean up in the image?

Alpine should still be very small according to the docker image (they say 5MB) and hitch itself should be minimal as well. Might be that I forgot to clean up some things during the build process.

**Comment by gnarea** [comment]
I'm not familiar with Hitch and I'm just playing with this image, so I don't have the full context, but the following layer makes up nearly all the space:

```
|1 HITCH_VERSION=1.6.0 /bin/sh -c apk --update add bash build-base libev libev-dev automake openssl openssl-dev autoconf curl byacc flex
```

... And I'd imagine many of those dependencies are not needed at run-time so they could be removed (e.g., bash, build-base).

**Comment by ktk** [comment]
True, will see if we can remove them again
